name: Build Folia image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'containers/folia*'
      - 'packages/folia*'
  push:
    branches:
      - main
    paths:
      - 'containers/folia*'
      - 'packages/folia*'
  schedule:
    - cron: '0 0 * * TUE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/reusable-image.yml
    secrets: inherit
    with:
      image-name: folia
      image-title: Folia
      image-desc: Folia MC images built for supply chain security (EXPERIMENTAL)
      default-tag: 1.21.4
