name: Build Paper image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'containers/paper*'
      - 'packages/paper*'
  push:
    branches:
      - main
    paths:
      - 'containers/paper*'
      - 'packages/paper*'
  schedule:
    - cron: '0 0 * * TUE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/reusable-image.yml
    secrets: inherit
    with:
      image-name: paper
      image-title: Paper
      image-desc: Paper MC images built for supply chain security
      default-tag: 1.21.7
